
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 26 08:05:11 COT 2024
//----------------------------------------------------

package analizadorsintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int nombre = 32;
  public static final int para = 14;
  public static final int tipo = 4;
  public static final int paso = 16;
  public static final int coma = 29;
  public static final int numero = 30;
  public static final int mientras = 12;
  public static final int sino = 9;
  public static final int hacer = 11;
  public static final int fin_programa = 3;
  public static final int finSegun = 20;
  public static final int asignacion = 27;
  public static final int parentesisIzquierdo = 21;
  public static final int programa = 2;
  public static final int finSi = 10;
  public static final int segun = 18;
  public static final int finPara = 17;
  public static final int deOtroModo = 19;
  public static final int parentesisDerecho = 22;
  public static final int constanteAlfanumerica = 34;
  public static final int operadorLogico = 24;
  public static final int EOF = 0;
  public static final int entonces = 8;
  public static final int escribir = 6;
  public static final int hasta = 15;
  public static final int error = 1;
  public static final int finMientras = 13;
  public static final int dosPuntos = 28;
  public static final int puntoComa = 26;
  public static final int leer = 5;
  public static final int si = 7;
  public static final int finNombre = 33;
  public static final int operadorAritmetico = 23;
  public static final int operadorRelacional = 25;
  public static final int identificador = 31;
}

